version: '3.8'

services:
  mcdonalds-coupon-claimer:
    # build: .  # <-- 如果你想自己编译，用这行
    image: ghcr.io/noxenys/mcdonalds:2.0.13 # <-- 直接用现成的镜像
    container_name: mcd_coupon_claimer
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # You can override env vars here if you don't use .env file
      - TZ=Asia/Shanghai
      - DB_PATH=/app/data/users.db
    volumes:
      - ./data:/app/data
